### PR TITLE
Bump jsonschema version, closes #26

### LINKED ISSUE #26: update jsonschema version
At the time of writing, [jsonschema latest release is 4.2.1](https://github.com/Julian/jsonschema/releases/).
Any reason why not to update to the latest version? If that is ok, I can open a pull request.

https://github.com/sirosen/check-jsonschema/blob/3662354a762060f5bcf155a7d962fe87c04cab31/setup.cfg#L21

### PR DESCRIPTION
**Pull request by foolioo**

### CODE REVIEW

**Comment by foolioo** [comment]
@sirosen: Do you have any idea why the workflows fail?

**Comment by foolioo** [comment]
@sirosen: Your assistance would be appreciated

**Comment by sirosen** [comment]
My _guess_ (and this really is a guess) based on the test failure output is that `jsonschema` bumped the default draft version used when a schema doesn't specify a version, and that one of the test schemas is invalid.

I should be able to look into it in the next few days.

**Comment by sirosen** [comment]
I just took care of the update, which I'll release in v0.8.0 shortly.

The issue turned out to be the lower bound of `jsonschema>=4`. Support for python3.6 was dropped from `jsonschema`, but I'm not ready to drop support here, so both `jsonschema` version 3 and version 4 need to be supported for now.

**Pull request closed without merging**
